dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "9"
cache:
  directories:
    - node_modules
matrix:
  fast_finish: true
before_script:
  - truffle version
script:
  - npm run lint
  - npm run lint:sol
  - npm run test
after_script:
  - npm run coverage && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
notifications:
  email:pw
    - ponzitrust.com@gmail.com