dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "9"
cache:
  directories:
    - node_modules
env:
  -
  - SOLIDITY_COVERAGE=true
matrix:
  fast_finish: true
  allow_failures:
    - env: SOLIDITY_COVERAGE=true
before_script:
  - truffle version
script:
  - npm run lint
  - npm run lint:sol
  - npm run test
notifications:
  email:pw
    - ponzitrust.com@gmail.com
